import type { Metadata } from "next";
import Link from "next/link";
import { Bungee } from "next/font/google";
import Header from "@/components/Header";
import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-brand",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});

const logoFont = Bungee({
  variable: "--font-logo",
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${geistSans.variable} ${geistMono.variable} ${logoFont.variable} bg-brand-bg text-brand-text`}>
  <Header />

        <main className="min-h-[calc(100dvh-140px)]">{children}</main>

        <footer className="mt-10 border-t border-brand-border bg-brand-header">
          <div className="mx-auto max-w-6xl px-4 py-6 text-sm text-brand-muted flex flex-col sm:flex-row items-center justify-between gap-2">
            <p>&copy; {new Date().getFullYear()} Sex Workers Advocacy Coalition DC</p>
            <p>
              <a className="text-brand-link hover:underline" href="https://www.swacdc.org/" target="_blank" rel="noopener noreferrer">swacdc.org</a>
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
 