import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-brand",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${geistSans.variable} ${geistMono.variable} bg-brand-bg text-brand-text`}>
        <header className="border-b border-brand-border bg-brand-header">
          <div className="mx-auto max-w-6xl px-4 py-4 flex items-center justify-between">
            <a href="https://www.swacdc.org/" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-3">
              <div className="h-2.5 w-2.5 rounded-full bg-brand-accent shadow-[0_0_0_4px_rgba(220,38,38,0.15)]" aria-hidden />
              <span className="text-lg font-semibold tracking-wide">SWAC DC</span>
            </a>
            <nav className="hidden sm:flex items-center gap-6 text-sm text-brand-muted">
              <Link className="hover:text-brand-accent" href="/">Home</Link>
              <a className="hover:text-brand-accent" href="https://www.swacdc.org/about" target="_blank" rel="noopener noreferrer">About</a>
              <a className="hover:text-brand-accent" href="https://www.swacdc.org/contact" target="_blank" rel="noopener noreferrer">Contact</a>
            </nav>
          </div>
        </header>

        <main className="min-h-[calc(100dvh-140px)]">{children}</main>

        <footer className="mt-10 border-t border-brand-border bg-brand-header">
          <div className="mx-auto max-w-6xl px-4 py-6 text-sm text-brand-muted flex flex-col sm:flex-row items-center justify-between gap-2">
            <p>&copy; {new Date().getFullYear()} Sex Workers Advocacy Coalition DC</p>
            <p>
              <a className="text-brand-link hover:underline" href="https://www.swacdc.org/" target="_blank" rel="noopener noreferrer">swacdc.org</a>
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
 